### ISSUE TITLE
[BUG] AccessDeniedException: /workdir/.scannerwork

### ISSUE THREAD

**Issue by Levence** [wayfair-contribs/sonarscanner-buildkite-plugin#6]
## Describe the bug

Receiving an AccessDenied exception to the workdir when using the sonarscannerbuildkite/sonarscanner container.

It looks as though sonarscannerbuildkite/sonarscanner-dotnet includes the following:

```
WORKDIR /workdir
RUN chown -R sonar:sonar /workdir
```

However this is not present in the regular sonarscanner container.

## To Reproduce

```
  - label: ":sonarqube: Sonarcloud PR scan"
    if: |
      // Only run for PR builds
      build.pull_request.id != null &&
        build.branch != "master"
    plugins:
      - ssh://git@github.com/wayfair-contribs/sonarscanner-buildkite-plugin.git#v0.1.0:
          sonarqube_host: https://sonarcloud.io
          project_key: XXX
          artifacts: coverage-reports/*.xml
          enable_pull_request_scan: true
          uses_community_edition: false
          additional_flags:
            - -Dsonar.python.coverage.reportPaths=coverage-reports/coverage-report.xml
            - -Dsonar.python.xunit.reportPath=coverage-reports/test-report.xml
            - -Dsonar.tests=tests
            - -Dsonar.organization=XXX
            - -Dsonar.pullrequest.key=$BUILDKITE_PULL_REQUEST
            - -Dsonar.pullrequest.branch=$BUILDKITE_BRANCH
            - -Dsonar.pullrequest.base=$BUILDKITE_PULL_REQUEST_BASE_BRANCH
    soft_fail: # Ensures a Sonarqube error does not fail the pipeline
      - exit_status: "*"
```

## Error

```
INFO: Base dir: /workdir
INFO: Working dir: /workdir/.scannerwork
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 53.158s
INFO: Final Memory: 7M/30M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.scan.ProjectLock
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:51)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at org.sonar.core.platform.ComponentContainer.getComponentByType(ComponentContainer.java:272)
	at org.sonar.scanner.scan.ProjectScanContainer.doBeforeStart(ProjectScanContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:120)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:108)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:127)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:122)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:108)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:58)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:52)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Failed to create work directory
	at org.sonar.scanner.scan.ProjectLock.<init>(ProjectLock.java:25)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:49)
	... 22 more
Caused by: java.nio.file.AccessDeniedException: /workdir/.scannerwork
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:689)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
	at java.base/java.nio.file.Files.createDirectories(Files.java:782)
	at org.sonar.scanner.scan.ProjectLock.<init>(ProjectLock.java:22)
	... 36 more
```

## Additional information (if any)

I've worked around the issue for now by specifying the workdir as /home/sonar, however this introduces some problems with having no access to the /home/sonar/artifacts-tmp.XXXXXXXXXX directory, meaning I can't perform a scan at the /home/sonar level, and need to specify sources as /home/sonar/src.

**Comment by jamescurtin** [comment]
Thanks for reporting! Fixed this issue & published an updated image.

**Comment by Levence** [comment]
Works perfectly thanks!
